version: '3.8'

networks:
  ros2-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/24

services:
  gazebo:
    image: vision-vrena-2025:v0.1.3
    container_name: gazebo
    hostname: gazebo
    networks:
      ros2-network:
        ipv4_address: 172.30.0.10
    environment:
      - ROS_DOMAIN_ID=55
      - ROS_LOCALHOST_ONLY=0
      - GAZEBO_MASTER_URI=http://localhost:11345
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - XAUTHORITY=/tmp/.docker.xauth
      - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ${XAUTHORITY}:/tmp/.docker.xauth
    working_dir: /home/va/Vision-Vrena-2025
    command: >
      bash -c "
        cd /home/va/Vision-Vrena-2025 && ls  &&
        source install/setup.bash &&
        export GAZEBO_MODE=headless &&  
        ros2 launch camera_sim_pkg camera.launch.py width:=640 height:=640 fps:=50
      "
    tty: true
    stdin_open: true
    restart: unless-stopped
    privileged: true

  vision_node:
    image: vision-vrena-2025:v0.1.3
    container_name: vision_node
    hostname: vision_node
    networks:
      ros2-network:
        ipv4_address: 172.30.0.12
    environment:
      - ROS_DOMAIN_ID=55
      - ROS_LOCALHOST_ONLY=0
      - GAZEBO_MASTER_URI=http://172.30.0.10:11345
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - XAUTHORITY=/tmp/.docker.xauth
      - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ${XAUTHORITY}:/tmp/.docker.xauth
      - /home/astra/team/competition/teamX_challenge/src/teamx_challenge/numbers:/home/va/templates:ro
      # 同时挂载整个工作空间
      - /home/astra/team/competition/teamX_challenge:/home/va/teamx_ws:rw
    working_dir: /home/va/teamx_ws
    command: >
     bash -c "
      source /opt/ros/humble/setup.bash &&
      echo '=== 构建 teamx_challenge 包 ===' &&
      colcon build --packages-select teamx_challenge || echo '构建完成' &&
      echo '=== 检查包 ===' &&
      echo '=== 启动节点 ===' &&
      source install/setup.bash &&
      ros2 run teamx_challenge vision_node 
     "
    # 选手在使用时 ros2 run player_pkg TestNode 将 TestNode 换为选手要启动的节点名字即可
    tty: true
    stdin_open: true
    restart: unless-stopped
    depends_on:
      - gazebo

  referee:
    image: vision-vrena-2025:v0.1.3
    container_name: referee
    hostname: referee
    networks:
      ros2-network:
        ipv4_address: 172.30.0.11
    environment:
      - ROS_DOMAIN_ID=55
      - ROS_LOCALHOST_ONLY=0
    working_dir: /home/va/Vision-Vrena-2025
    command: >
      bash -c "
        cd /home/va/Vision-Vrena-2025 && ls && 
        source install/setup.bash &&
        ros2 launch referee_pkg referee_pkg_launch.xml 
        "
    tty: true
    stdin_open: true
    restart: unless-stopped
    depends_on:
      - gazebo
      - vision_node
